owner: envesko
repo: status-ec

sites:
  - name: Envesko Cloud - HTTPS
    url: https://envesko.cloud
  - name: Song Command API
    url: https://envesko.cloud/api/esm/spotify/get-current-song
    headers:
      - "Authorization: Bearer $ESM_TOKEN"
      - "Content-Type: application/json"
    ___dangerous__body_degraded: "Day Error Rate Above 5%"
    ___dangerous__body_down: "Hour Error Rate Above 5%"
  - name: Clip Command API
    url: https://envesko.cloud/api/esm/twitch/create-clip
    headers:
      - "Authorization: Bearer $ESM_TOKEN"
      - "Content-Type: application/json"
    ___dangerous__body_degraded: "Day Error Rate Above 5%"
    ___dangerous__body_down: "Hour Error Rate Above 5%"

status-website:
  cname: status.envesko.cloud
  name: Envesko Cloud Status
  introTitle: "**Envesko Cloud** Status Monitor"
  introMessage: Incidents are tracked automatically by our system. If you encounter a problem with the platform, please [Open an Incident Report](https://github.com/envesko/status/issues/new/choose) or [Open a Ticket](https://base.envesko.com/contact.php).
  logoUrl: https://github.com/envesko/status-ec/blob/master/assets/logo.png
  favicon: https://github.com/envesko/status-ec/blob/master/assets/favicon.png
  navbar:
    - title: Status
      href: /
    - title: Open Incident
      href: https://github.com/$OWNER/$REPO/issues/new/choose
    - title: Open Ticket
      href: https://base.envesko.com/contact.php
    - title: Discord
      href: https://discord.gg/7zD8qBspuy
  assignees:
    - Brandin
  theme: night
  i18n:
    footer: Powered by [Envesko](https://envesko.com)